DOCTORS = [
    {
                "id": 1,
        "name": "Dr. Sarah Jamade",
        "specialization": "Neurologist",
        "contact": "+91 9923567480",
        "email": "sarah.j@medcare.com",
        "address": "123 Medical St, Health City, nashik 429940",
        "availability": "Mon-Fri: 9AM-5PM",
        "experience": "15 years",
        "rating": 4.8,
        "fee": "₹1500",
        "symptoms": ["headache", "migraine", "dizziness", "seizures", "memory loss"],
        "image": "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 2,
        "name": "Dr. manish jadhav",
        "specialization": "Cardiologist",
        "contact": "+91 9923467590",
        "email": "manish.c@heartcare.com",
        "address": "456 Heart Ave, township, nashik 20002",
        "availability": "Mon-Sat: 10AM-6PM",
        "experience": "12 years",
        "rating": 4.9,
        "fee": "₹2000",
        "symptoms": ["chest pain", "palpitations", "shortness of breath", "high BP"],
        "image": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 3,
        "name": "Dr. Priya Sharma",
        "specialization": "Dermatologist",
        "contact": "+91 8899675437",
        "email": "priya.s@skincare.com",
        "address": "789 Skin Lane, Dermacity, nashik 30003",
        "availability": "Tue-Sat: 9AM-7PM",
        "experience": "10 years",
        "rating": 4.7,
        "fee": "₹1200",
        "symptoms": ["skin rash", "acne", "allergy", "itching", "eczema"],
        "image": "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 4,
        "name": "Dr. Rohit shinde",
        "specialization": "Orthopedic",
        "contact": "+91 9923468765",
        "email": "rohit.b@bonecare.com",
        "address": "101 Bone Street, Joint City, nashik 40004",
        "availability": "Mon-Fri: 8AM-4PM",
        "experience": "18 years",
        "rating": 4.9,
        "fee": "₹2500",
        "symptoms": ["joint pain", "back pain", "fracture", "arthritis", "sports injury"],
        "image": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 5,
        "name": "Dr. Lisa Wagh",
        "specialization": "Pediatrician",
        "contact": "+91 9967540065",
        "email": "lisa.w@childcare.com",
        "address": "202 Child Care Road, Kids Town, Kolkata 50005",
        "availability": "Mon-Sun: 10AM-8PM",
        "experience": "14 years",
        "rating": 4.8,
        "fee": "₹1000",
        "symptoms": ["child fever", "vaccination", "growth issues", "cough", "cold"],
        "image": "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 6,
        "name": "Dr. Raj Patel",
        "specialization": "General Physician",
        "contact": "+91 8798675743",
        "email": "raj.p@familycare.com",
        "address": "303 Family Clinic, Care City, nashik 60006",
        "availability": "24/7 Emergency",
        "experience": "20 years",
        "rating": 4.9,
        "fee": "₹800",
        "symptoms": ["fever", "cold", "cough", "general checkup", "vaccination"],
        "image": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 7,
        "name": "Dr. Anjali Deshpande",
        "specialization": "Gynecologist",
        "contact": "+91-9876543210",
        "email": "anjali.d@womenscare.com",
        "address": "Women's Health Center, Mumbai",
        "availability": "Mon-Sat: 10AM-6PM",
        "experience": "12 years",
        "rating": 4.8,
        "fee": "₹1800",
        "symptoms": ["pregnancy", "menstrual", "pcos", "menopause", "women health"],
        "image": "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=400&fit=crop&crop=face"

    },
    {
        "id": 8,
        "name": "Dr. Jayesh kadge",
        "specialization": "Gastroenterologist",
        "contact": "+91 7868567456",
        "email": "jayesh.w@digestcare.com",
        "address": "404 Digestive Center, Gut City, mumbai 70007",
        "availability": "Mon-Fri: 9AM-5PM",
        "experience": "16 years",
        "rating": 4.7,
        "fee": "₹2200",
        "symptoms": ["stomach pain", "vomiting", "diarrhea", "acid reflux", "ibs"],
        "image": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 9,
        "name": "Dr. Emily james",
        "specialization": "Psychiatrist",
        "contact": "+91 7986543298",
        "email": "emily.c@mentalhealth.com",
        "address": "505 Mind Clinic, Peace Town, PT 80008",
        "availability": "Tue-Sat: 11AM-7PM",
        "experience": "13 years",
        "rating": 4.9,
        "fee": "₹2800",
        "symptoms": ["anxiety", "depression", "stress", "insomnia", "mood swings"],
        "image": "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 10,
        "name": "Dr. daksh kshetri",
        "specialization": "ENT Specialist",
        "contact": "+91 9978654390",
        "email": "daksh.k@entcare.com",
        "address": "606 ENT Center, Ear Nose Throat City, mumbai 90009",
        "availability": "Mon-Sat: 10AM-6PM",
        "experience": "11 years",
        "rating": 4.6,
        "fee": "₹1600",
        "symptoms": ["ear pain", "sore throat", "sinus", "hearing loss", "tonsillitis"],
        "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face"

    },
    {
        "id": 11,
        "name": "Dr. mansi hengade",
        "specialization": "Endocrinologist",
        "contact": "+91 7986543298",
        "email": "mansi.r@hormonecare.com",
        "address": "707 Hormone Center, Balance City, nashik 10010",
        "availability": "Mon-Fri: 9AM-5PM",
        "experience": "14 years",
        "rating": 4.8,
        "fee": "₹2400",
        "symptoms": ["diabetes", "thyroid", "weight gain", "hormonal imbalance", "pcos"],
        "image": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 12,
        "name": "Dr. abhinav kasabe",
        "specialization": "Urologist",
        "contact": "+91 789654398",
        "email": "abhinav.s@urocare.com",
        "address": "808 Urology Center, Kidney City, kolkata 11011",
        "availability": "Mon-Sat: 9AM-6PM",
        "experience": "17 years",
        "rating": 4.7,
        "fee": "₹2600",
        "symptoms": ["urinary infection", "kidney stones", "prostate", "bladder issues"],
        "image": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 13,
        "name": "Dr. Sophia shinde",
        "specialization": "Ophthalmologist",
        "contact": "+91 9879897657",
        "email": "sophia.l@eyecare.com",
        "address": "909 Eye Care Center, Vision City, VC 12012",
        "availability": "Mon-Fri: 10AM-6PM",
        "experience": "15 years",
        "rating": 4.9,
        "fee": "₹1900",
        "symptoms": ["eye pain", "blurred vision", "red eyes", "cataract", "glaucoma"],
        "image": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 14,
        "name": "Dr. raghav ravi",
        "specialization": "Dentist",
        "contact": "+1-555-6677",
        "email": "raghav.b@dentalcare.com",
        "address": "1010 Dental Clinic, Smile City, mumbai 13013",
        "availability": "Mon-Sat: 9AM-7PM",
        "experience": "19 years",
        "rating": 4.8,
        "fee": "₹1200",
        "symptoms": ["toothache", "gum pain", "cavity", "teeth cleaning", "wisdom tooth"],
        "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 15,
        "name": "Dr. Fatima Khan",
        "specialization": "Pulmonologist",
        "contact": "+91-9876543211",
        "email": "fatima.k@lungcare.com",
        "address": "Lung Care Center, Delhi",
        "availability": "Mon-Sat: 10AM-6PM",
        "experience": "16 years",
        "rating": 4.7,
        "fee": "₹2100",
        "symptoms": ["asthma", "breathing difficulty", "chronic cough", "tb", "lung infection"],
        "image": "https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 16,
        "name": "Dr. Arjun Mehta",
        "specialization": "Oncologist",
        "contact": "+91-9876543212",
        "email": "arjun.m@cancercare.com",
        "address": "Cancer Care Hospital, Bangalore",
        "availability": "Mon-Fri: 9AM-5PM",
        "experience": "18 years",
        "rating": 4.9,
        "fee": "₹3500",
        "symptoms": ["cancer screening", "chemotherapy", "tumor", "cancer treatment"],
        "image": "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 17,
        "name": "Dr. Nisha Verma",
        "specialization": "Rheumatologist",
        "contact": "+91-9876543213",
        "email": "nisha.v@jointcare.com",
        "address": "Arthritis Center, Chennai",
        "availability": "Mon-Sat: 10AM-6PM",
        "experience": "14 years",
        "rating": 4.6,
        "fee": "₹2300",
        "symptoms": ["arthritis", "joint swelling", "lupus", "autoimmune", "fibromyalgia"],
        "image": "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 18,
        "name": "Dr. Sanjay Kumar",
        "specialization": "Nephrologist",
        "contact": "+91-9876543214",
        "email": "sanjay.k@kidneycare.com",
        "address": "Kidney Hospital, Hyderabad",
        "availability": "Mon-Fri: 9AM-5PM",
        "experience": "17 years",
        "rating": 4.8,
        "fee": "₹2700",
        "symptoms": ["kidney disease", "dialysis", "kidney failure", "urinary problems"],
        "image": "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 19,
        "name": "Dr. Meera Reddy",
        "specialization": "Hematologist",
        "contact": "+91-9876543215",
        "email": "meera.r@bloodcare.com",
        "address": "Blood Disorder Center, Kolkata",
        "availability": "Mon-Sat: 10AM-6PM",
        "experience": "15 years",
        "rating": 4.7,
        "fee": "₹2900",
        "symptoms": ["anemia", "blood cancer", "bleeding disorder", "clotting issues"],
        "image": "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 20,
        "name": "Dr. Vikram Singh",
        "specialization": "Surgeon",
        "contact": "+91-9876543216",
        "email": "vikram.s@surgerycare.com",
        "address": "Surgical Center, Pune",
        "availability": "24/7 Emergency",
        "experience": "21 years",
        "rating": 4.9,
        "fee": "₹4000",
        "symptoms": ["surgery", "appendicitis", "gallstones", "hernia", "emergency surgery"],
        "image": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face"
    },
    {
        "id": 21,
        "name": "Dr. Maya shinde",
        "specialization": "Dermatologist",
        "contact": "+91 8979678989",
        "email": "maya.m@skinspecialist.com",
        "address": "111 Skin Care Center, Glow City, GC 14014",
        "availability": "Mon-Fri: 10AM-7PM",
        "experience": "9 years",
        "rating": 4.5,
        "fee": "₹1100",
        "symptoms": ["psoriasis", "vitiligo", "hives", "skin infection", "hair fall"],
        "image": "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face"
    }
]

# Symptom to specialization mapping
SYMPTOM_SPECIALIZATION = {
    "headache": "Neurologist",
    "migraine": "Neurologist",
    "dizziness": "Neurologist",
    "seizures": "Neurologist",
    "memory loss": "Neurologist",
    
    "chest pain": "Cardiologist",
    "palpitations": "Cardiologist",
    "shortness of breath": "Cardiologist",
    "high bp": "Cardiologist",
    "heart pain": "Cardiologist",
    
    "skin rash": "Dermatologist",
    "acne": "Dermatologist",
    "itching": "Dermatologist",
    "allergy": "Dermatologist",
    "eczema": "Dermatologist",
    
    "joint pain": "Orthopedic",
    "back pain": "Orthopedic",
    "fracture": "Orthopedic",
    "arthritis": "Orthopedic",
    "sports injury": "Orthopedic",
    
    "fever": "General Physician",
    "cold": "General Physician",
    "cough": "General Physician",
    "general checkup": "General Physician",
    "vaccination": "General Physician",
    
    "pregnancy": "Gynecologist",
    "menstrual": "Gynecologist",
    "pcos": "Gynecologist",
    "menopause": "Gynecologist",
    "women health": "Gynecologist",
    
    "stomach pain": "Gastroenterologist",
    "vomiting": "Gastroenterologist",
    "diarrhea": "Gastroenterologist",
    "acid reflux": "Gastroenterologist",
    "ibs": "Gastroenterologist",
    
    "anxiety": "Psychiatrist",
    "depression": "Psychiatrist",
    "stress": "Psychiatrist",
    "insomnia": "Psychiatrist",
    "mood swings": "Psychiatrist",
    
    "ear pain": "ENT Specialist",
    "sore throat": "ENT Specialist",
    "sinus": "ENT Specialist",
    "hearing loss": "ENT Specialist",
    "tonsillitis": "ENT Specialist",
    
    "diabetes": "Endocrinologist",
    "thyroid": "Endocrinologist",
    "weight gain": "Endocrinologist",
    "hormonal imbalance": "Endocrinologist",
    
    "urinary infection": "Urologist",
    "kidney stones": "Urologist",
    "prostate": "Urologist",
    "bladder issues": "Urologist",
    
    "eye pain": "Ophthalmologist",
    "blurred vision": "Ophthalmologist",
    "red eyes": "Ophthalmologist",
    "cataract": "Ophthalmologist",
    "glaucoma": "Ophthalmologist",
    
    "toothache": "Dentist",
    "gum pain": "Dentist",
    "cavity": "Dentist",
    "teeth cleaning": "Dentist",
    
    "asthma": "Pulmonologist",
    "breathing difficulty": "Pulmonologist",
    "chronic cough": "Pulmonologist",
    "tb": "Pulmonologist",
    "lung infection": "Pulmonologist",
    
    "cancer screening": "Oncologist",
    "chemotherapy": "Oncologist",
    "tumor": "Oncologist",
    
    "joint swelling": "Rheumatologist",
    "lupus": "Rheumatologist",
    "autoimmune": "Rheumatologist",
    "fibromyalgia": "Rheumatologist",
    
    "kidney disease": "Nephrologist",
    "dialysis": "Nephrologist",
    "kidney failure": "Nephrologist",
    
    "anemia": "Hematologist",
    "blood cancer": "Hematologist",
    "bleeding disorder": "Hematologist",
    
    "surgery": "Surgeon",
    "appendicitis": "Surgeon",
    "gallstones": "Surgeon",
    "hernia": "Surgeon",
    "emergency surgery": "Surgeon",
    
    "child fever": "Pediatrician",
    "growth issues": "Pediatrician"
}

# Specialization list for dropdown
SPECIALIZATIONS = [
    "Neurologist",
    "Cardiologist",
    "Dermatologist",
    "Orthopedic",
    "Pediatrician",
    "General Physician",
    "Gynecologist",
    "Gastroenterologist",
    "Psychiatrist",
    "ENT Specialist",
    "Endocrinologist",
    "Urologist",
    "Ophthalmologist",
    "Dentist",
    "Pulmonologist",
    "Oncologist",
    "Rheumatologist",
    "Nephrologist",
    "Hematologist",
    "Surgeon"
]